### ISSUE TITLE
Update from 0.2.1 --> 0.2.2 requires unexpected dependency

### ISSUE THREAD

**Issue by rdlugosz** [SciRuby/minimization#8]
The `rb-gsl` gem is introduced as a requirement when updating the gem from `0.2.1` to `0.2.2`. This is unexpected in a Patch level release. Please see notes in [the similar issue in statsample](https://github.com/SciRuby/statsample/issues/28).

Diff when updating:

```
-    minimization (0.2.1)
+    minimization (0.2.2)
+      rb-gsl (~> 1.2)
       text-table (~> 1.2)
```

**Comment by agarie** [comment]
I fixed this issue on the latest version.
